-- 004_immutable_evidence_ledger.sql
-- Append-only ledger with provenance, classification version tags, supersession, and hash chain.

BEGIN;

CREATE TABLE IF NOT EXISTS evidence.ledger_events (
  event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  patient_id UUID REFERENCES core.patients(patient_id) ON DELETE RESTRICT,
  observed_at TIMESTAMPTZ NOT NULL,
  ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  domain evidence.ledger_domain NOT NULL,
  data_element JSONB NOT NULL,
  normalized_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_attribution evidence.source_attribution NOT NULL,
  source_system_id UUID REFERENCES ingestion.source_systems(source_system_id) ON DELETE SET NULL,
  raw_resource_id UUID REFERENCES ingestion.raw_resources(raw_resource_id) ON DELETE SET NULL,
  source_document_id UUID REFERENCES literature.documents(document_id) ON DELETE SET NULL,
  source_claim_id UUID REFERENCES literature.phenotype_claims(claim_id) ON DELETE SET NULL,
  provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
  certainty_level NUMERIC(5,4) NOT NULL DEFAULT 1.0 CHECK (certainty_level BETWEEN 0 AND 1),
  validation_status evidence.validation_status NOT NULL DEFAULT 'raw',
  nosology_version_id UUID REFERENCES nosology.framework_versions(nosology_version_id) ON DELETE SET NULL,
  supersedes_event_id UUID REFERENCES evidence.ledger_events(event_id) ON DELETE RESTRICT,
  ingestion_run_id UUID REFERENCES ingestion.ingestion_runs(ingestion_run_id) ON DELETE SET NULL,
  inserted_by TEXT,
  request_id TEXT,
  hash_prev TEXT,
  hash_self TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((patient_id IS NOT NULL) OR (domain = 'literature_claim'))
);

CREATE OR REPLACE FUNCTION evidence.set_ledger_event_hash()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  previous_hash TEXT;
  payload TEXT;
BEGIN
  -- Global lock produces a deterministic append order for the tamper-evident chain.
  PERFORM pg_advisory_xact_lock(892347001);

  IF NEW.hash_prev IS NULL THEN
    SELECT le.hash_self
      INTO previous_hash
      FROM evidence.ledger_events le
      ORDER BY le.event_seq DESC
      LIMIT 1;
    NEW.hash_prev := previous_hash;
  END IF;

  payload :=
    coalesce(NEW.hash_prev, '') || '|' ||
    NEW.event_id::text || '|' ||
    coalesce(NEW.patient_id::text, '') || '|' ||
    NEW.observed_at::text || '|' ||
    NEW.ingested_at::text || '|' ||
    NEW.domain::text || '|' ||
    NEW.data_element::text || '|' ||
    NEW.normalized_codes::text || '|' ||
    NEW.source_attribution::text || '|' ||
    coalesce(NEW.source_system_id::text, '') || '|' ||
    coalesce(NEW.raw_resource_id::text, '') || '|' ||
    coalesce(NEW.source_document_id::text, '') || '|' ||
    coalesce(NEW.source_claim_id::text, '') || '|' ||
    NEW.provenance::text || '|' ||
    NEW.certainty_level::text || '|' ||
    NEW.validation_status::text || '|' ||
    coalesce(NEW.nosology_version_id::text, '') || '|' ||
    coalesce(NEW.supersedes_event_id::text, '');

  NEW.hash_self := encode(digest(payload, 'sha256'), 'hex');
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION evidence.prevent_ledger_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'evidence.ledger_events is append-only; insert a superseding event instead of UPDATE/DELETE';
END $$;

DROP TRIGGER IF EXISTS trg_ledger_events_hash ON evidence.ledger_events;
CREATE TRIGGER trg_ledger_events_hash
BEFORE INSERT ON evidence.ledger_events
FOR EACH ROW EXECUTE FUNCTION evidence.set_ledger_event_hash();

DROP TRIGGER IF EXISTS trg_ledger_events_no_update ON evidence.ledger_events;
CREATE TRIGGER trg_ledger_events_no_update
BEFORE UPDATE OR DELETE ON evidence.ledger_events
FOR EACH ROW EXECUTE FUNCTION evidence.prevent_ledger_mutation();

CREATE TABLE IF NOT EXISTS evidence.ledger_event_notes (
  note_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES evidence.ledger_events(event_id) ON DELETE RESTRICT,
  note_text TEXT NOT NULL,
  note_kind TEXT NOT NULL DEFAULT 'curator_note',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMIT;

